[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/espnapi/*"
  to = "https://site.api.espn.com/apis/site/v2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/nbaapi/*"
  to = "http://rest.nbaapi.com/api/:splat"
  status = 200
  force = true
